name: Elections
version: '${version}'
main: net.democracycraft.elections.Elections
api-version: '1.21'
commands:
  democracyelections:
    description: Elections commands (manager UI, export data)
    usage: /<command>
    aliases: [elections]
    permission: elections.user
permissions:
  elections.admin:
    description: Grants all Elections permissions
    default: op
    children:
      elections.manager: true
      elections.user: true
      elections.paste: true
      elections.health: true
  elections.manager:
    description: Manage elections (open manager, create, edit, open/close)
    default: op
    children:
      elections.user: true
  elections.user:
    description: Use election features as a player
    default: true
  elections.permissions.reload:
    description: Reload the permission nodes configuration
    default: op
  elections.paste:
    description: Manage paste operations (delete)
    default: op
  elections.health:
    description: View elections health stats
    default: op