name: Elections
version: '${version}'
main: net.democracycraft.elections.Elections
api-version: '1.21'
authors: [ Alepando ]
commands:
  elections:
    description: Elections commands (manager UI, export data)
    usage: /<command>
    permission: elections.command
permissions:
  elections.admin:
    description: Grants all Elections permissions
    default: op
    children:
      elections.command: true
      elections.manager: true
      elections.export: true
      elections.permissions.reload: true
      elections.paste: true
      elections.health: true
      elections.user: true
  elections.manager:
    description: Manage elections (open manager, create, edit, open/close)
    default: op
    children:
      elections.command: true
      elections.export: true
      elections.health: true
      elections.permissions.reload: true
  elections.command:
    description: Access to /elections command entrypoint
    default: op
  elections.export:
    description: Export elections data (remote/local/both, admin modes, dispatch)
    default: op
  elections.user:
    description: Use election features as a player (voting eligibility, non-command features)
    default: true
  elections.permissions.reload:
    description: Reload the permission nodes configuration
    default: op
  elections.paste:
    description: Manage paste operations (delete)
    default: op
  elections.health:
    description: View elections health stats
    default: op
